export const ROLE_GROUPS = {
  ADMIN: "ADMIN",
  OPERATOR: "OPERATOR",
  CUSTOMER: "CUSTOMER",
  ADMIN_OPERATOR: ["ADMIN", "OPERATOR"],
  ADMIN_OPERATOR_CUSTOMER: ["ADMIN", "OPERATOR", "CUSTOMER"],
};

export enum ROLES {
  CUSTOMER = "CUSTOMER",
  ADMIN = "ADMIN",
  OPERATOR = "OPERATOR",
}